import Head from "next/head";
import AppWrapper from "../components/common/AppWrapper";
import PlacesList from "../components/places/PlacesList";

export default function Home() {
  return (
    <AppWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlacesList />
    </AppWrapper>
  );
}
